### ISSUE TITLE
Opening application twice does not create a second instance of application.

### ISSUE THREAD

**Issue by emiljoha** [lujun9972/el-dmenu#5]
#### Summary:
Opening application twice does not create a second instance of application.

#### Steps to Reproduce:
1. M-x dmenu and type name of application and hit enter.
3. Applications starts as expected.
4  Again type M-x dmenu and type name of application and hit enter.

#### Expected Behavior:
A new window with a second instance of the programming running in it appears.

#### Observed Behavior: 
No new instance of the program is started and the *program-name* buffer shown.

#### Regression
Have had the issue since first installing el-dmenu some months ago.

#### Environment 
Opensuse Tumbelweed + Emacs X Window Manager (exwm)

**Comment by cryptorick** [comment]
This should be fixed via https://github.com/lujun9972/el-dmenu/commit/78b869e17c7dd3b714987ed4623ed32da0168665.  Please test.  It's in the master branch, so you should be able to just do a fetch or pull.

@lujun9972 I hope it was ok to put the change on the master branch.  Please let me know if you'd rather I follow another workflow.

**Comment by lujun9972** [comment]
@cryptorick  That's great, Thank you very much.
@emiljoha Is it what you want? Could the issue be closed?

**Comment by emiljoha** [comment]
@cryptorick Thank you very much! 
@lujun9972 Works like a charm. Closing the issue!
