### ISSUE TITLE
Opening file while in buffer of remote file failes.

### ISSUE THREAD

**Issue by emiljoha** [lujun9972/el-dmenu#6]
Trying to open firefox with M-x firefox while in a buffer displaying a file on the remote machine named <remote-machine> I get the following log:

```
Tramp: Opening connection for <remote-machine> using ssh...
Tramp: Sending command ‘exec ssh -q   -o ControlMaster=auto -o ControlPath='tramp.%C' -o ControlPersist=no -e none <remote-machine>’
Tramp: Waiting for prompts from remote shell...done
Tramp: Found remote shell prompt on ‘<remote-machine>’
Tramp: Opening connection for <remote-machine> using ssh...done
```

### Expected behaviour

Firefox window opens on local machine.

**Comment by cryptorick** [comment]
@emiljoha I don't have that in my Emacs, i.e., when I type `M-x firefox` and press `Enter`, Emacs echoes `[No match]`.  If you do have such an interactive function in your configuration, could you tell us how it relates to the functionality in `dmenu.el`?  I'm trying to determine if this is an issue for this project or not.  Thanks!

**Comment by lujun9972** [comment]
I think what @emiljoha  mean is `M-x dmenu <RET> firefox <RET>`
The reason is `make-comint` use `default-directory` of `process buffer` as the process work path
```
	(default-directory
	  (if (file-accessible-directory-p default-directory)
	      default-directory
	    "/"))
```
in the `comint-exec-1` function
So maybe we should check the `default-directory`, if it is a remote directory then change it to the root directory

**Comment by lujun9972** [comment]
@emiljoha This should be fixed now

**Comment by emiljoha** [comment]
>  I think what @emiljoha mean is M-x dmenu <RET> firefox <RET>

 Yes that is what I mean, not sure what I was thinking when I wrote that. Sorry for the caused confusion.

Tested the fix and it works like a charm. Awesome work! :medal_sports:  :star: 

Thank you @cryptorick and  @lujun9972 for taking the time fixing this issue and the other one I reported!
