### ISSUE TITLE
Duplicate entries

### ISSUE THREAD

**Issue by bandali** [lujun9972/el-dmenu#7]
Hi,

I’ve noticed that most but not all entries in `dmenu--cache-executable-files` have a duplicate.  Would be nice if the items were unique.

P.S. thanks for the awesome package :)

**Comment by cryptorick** [comment]
@bandali0 please close the issue once you are satisfied with the new commits (which @lujun9972 put on master). Thanks!

**Comment by bandali** [comment]
Thank you both @cryptorick and @lujun9972 for your help, it appears that both issues are now fixed.

Thanks again!
